# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
# cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod repo update
- pod install --project-directory=Example
- pod env
script:
- set -o pipefail && xcodebuild test -workspace Example/RLMObject-JSONAPI.xcworkspace -scheme RLMObject-JSONAPI-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty
- pod lib lint
